# Generated by Django 4.2.3 on 2023-07-18 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='imagen',
            field=models.ImageField(blank=True, default='usuarios/usuario_def.png', null=True, upload_to='usuarios'),
        ),
    ]
